### ISSUE TITLE
Vibration is too weak

### ISSUE THREAD

**Issue by pkonkka** [pedlarstudios/EggTimer#1]
Awesome timer, but the vibration is too weak. Is it possible to make it stronger?

**Comment by bhawker** [comment]
Yeah, I think most folks would probably agree with you based on feedback I see in general on Vivoactive's vibration being rather weak. I've made a change to use the maximum vibration power for all vibrations (starting a timer, stopping a timer, and when the timer finishes).

I might squeeze some other minor things in with that change before submitting a new update to the Connect IQ store - look for that something during this upcoming week. Thanks for the feedback!
