### ISSUE TITLE
Starting the timer

### ISSUE THREAD

**Issue by pkonkka** [pedlarstudios/EggTimer#2]
I normally use the same values in my timer. It would nice if I could start the timer immediately from the start button without pressing the check mark.

**Comment by bhawker** [comment]
Just to clarify, do you mean when a timer has finished (reaches 00:00), you'd like to press Start and have it essentially restart the timer with the last duration used?

**Comment by pkonkka** [comment]
I meant that user must always press Menu button after he opens the app, Would it be possible to start the previous timer in this screen?

**Comment by bhawker** [comment]
I've made two changes that should help:
- Pressing the Start button when the timer has elapsed (00:00) restarts it from your previous value
- If you re-open the app and the timer had previously elapsed, it now gets set to your previous value

This is now in version 0.7 published in the Connect store.

**Comment by pkonkka** [comment]
Hi,

I just installed the new version. It's awesome!
Thank you very much :)

Petri
